easy_admin:
    entities:
        Filter:
            class: 'KRG\CmsBundle\Entity\FilterInterface'
            list:
                fields:
                    - 'name'
                    - { property: 'seo', type: 'boolean' }
                    - { property: 'working', type: 'boolean' }
                    - 'enabled'
            form:
                fields:
                    - { type: 'group', label: 'Filter' }
                    - 'name'
                    - { type: 'group', label: 'Configuration' }
                    -
                        property: 'seo'
                        type: 'KRG\CmsBundle\Form\Type\SeoType'
                        label: false
                        type_options:
                            required_url: false
                    - { type: 'group', label: 'Form' }
                    - { property: 'form', type: 'KRG\CmsBundle\Form\Type\FilterType' }
                    - { type: 'group', label: 'Status' }
                    - 'enabled'
