easy_admin:
    entities:
        Menu:
            class: 'KRG\CmsBundle\Entity\MenuInterface'
            list:
                max_results: 100
                fields:
                    - { property: 'name', label: 'menu.name' }
                    - { property: 'url', label: 'menu.url' }
                    - { property: 'parent', label: 'menu.parent' }
                    - { property: 'enabled', label: 'menu.enabled' }
                sort: ['position', 'ASC']
            form:
                fields:
                    - { type: 'group', label: 'group.menu' }
                    -
                        property: 'name'
                        type: 'KRG\IntlBundle\Form\Type\TranslationType'
                        type_options:
                            entry_type: 'Symfony\Component\Form\Extension\Core\Type\TextType'
                    - { property: 'key', help: 'unique_key', label: 'menu.key'  }
                    - { property: 'parent', label: 'menu.parent', type_options: {'placeholder': ''} }
                    - 'icon'
                    - { type: 'group', label: 'group.configuration' }
                    -
                        property: 'route'
                        type: 'KRG\IntlBundle\Form\Type\TranslationType'
                        type_options:
                            entry_type: 'KRG\CmsBundle\Form\Type\UrlType'
                            label: false
                    - { type: 'group', label: 'group.status' }
                    - { property: 'enabled', label: 'menu.enabled' }
