easy_admin:
    entities:
        Page:
            class: 'KRG\CmsBundle\Entity\PageInterface'
            list:
                fields:
                    - 'name'
                    - 'seo.metaTitle'
                    - 'seo.url'
                    - 'enabled'
                actions:
                    - { name: 'clone', icon: 'clone', css_class: 'btn btn-secondary' }
            form:
                fields:
                    - { type: 'group', label: 'Page'}
                    - 'name'
                    -
                        property: 'content'
                        type: 'KRG\IntlBundle\Form\Type\TranslationType'
                        type_options:
                            entry_type: 'KRG\CmsBundle\Form\Type\ContentType'
                            label: false
                            entry_options:
                                fragment: false
                    - { type: 'group', label: 'Seo'}
                    -   property: 'seo' # MUST BE AFTER CONTENT
                        type: 'KRG\CmsBundle\Form\Type\SeoType'
                        label: false
                    - { type: 'group', label: 'Status' }
                    - 'enabled'
