easy_admin:
    entities:
        Seo:
            roles: ['ROLE_SEO']
            class: 'KRG\CmsBundle\Entity\SeoInterface'
            list:
                title: '<i class="fa fa-sitemap"></i> Seo'
                fields:
                    - { property: url, label: 'seo.url' }
                    - { property: routeName, label: 'seo.route' }
                    - { property: metaTitle, label: 'seo.metaTitle' }
                    - { property: metaDescription, label: 'seo.metaDescription' }
                    - enabled
            form:
                fields:
                    - { type: 'group', label: 'seo.configuration' }
                    - { property: route, type: KRG\CmsBundle\Form\Type\RouteType }
                    -
                        property: 'url'
                        type: 'KRG\IntlBundle\Form\Type\TranslationType'
                        type_options:
                            entry_type: 'Symfony\Component\Form\Extension\Core\Type\TextType'
                    - { type: 'group', label: 'seo.metas' }
                    -
                        property: 'metaTitle'
                        type: 'KRG\IntlBundle\Form\Type\TranslationType'
                        type_options:
                            entry_type: 'Symfony\Component\Form\Extension\Core\Type\TextType'
                    -
                        property: 'metaDescription'
                        type: 'KRG\IntlBundle\Form\Type\TranslationType'
                        type_options:
                            entry_type: 'Symfony\Component\Form\Extension\Core\Type\TextType'
                    - enabled
