easy_admin:
    entities:
        Seo:
            roles: ['ROLE_SEO']
            class: 'KRG\CmsBundle\Entity\SeoInterface'
            list:
                fields:
                    - 'url'
                    - 'routeName'
                    - 'metaTitle'
                    - 'enabled'
            form:
                fields:
                    - { type: 'group', label: 'Configuration' }
                    - { property: 'route', label: false }
                    -
                        property: 'url'
                        type: 'KRG\IntlBundle\Form\Type\TranslationType'
                        label: 'Url redirect'
                        type_options:
                            entry_type: 'Symfony\Component\Form\Extension\Core\Type\TextType'
                    - { type: 'group', label: 'Metas' }
                    -
                        property: 'metaTitle'
                        type: 'KRG\IntlBundle\Form\Type\TranslationType'
                        type_options:
                            entry_type: 'Symfony\Component\Form\Extension\Core\Type\TextType'
                    -
                        property: 'metaDescription'
                        type: 'KRG\IntlBundle\Form\Type\TranslationType'
                        type_options:
                            entry_type: 'Symfony\Component\Form\Extension\Core\Type\TextareaType'
                    - { type: 'group', label: 'Content' }
                    -
                        property: 'preContent'
                        type: 'KRG\CmsBundle\Form\Type\ContentType'
                        type_options:
                            height: 200
                    -
                        property: 'postContent'
                        type: 'KRG\CmsBundle\Form\Type\ContentType'
                        type_options:
                            height: 200
                    - { type: 'group', label: 'Status' }
                    - 'enabled'
