parameters:
    krg_seo.admin.seo.class: KRG\SeoBundle\Admin\SeoAdmin
    krg_seo.admin.seo_page.class: KRG\SeoBundle\Admin\SeoPageAdmin

services:
    krg_seo.admin.seo:
        class: %krg_seo.admin.seo.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: "SEO", label: "SEO" }
        arguments:
            - ~
            - '%krg_seo.seo_class%'
            - ~
        calls:
            - [setRouter, ['@router']]
            - [setClearCache, ['@krg_seo.clear_routing_cache']]

    krg_seo.admin.seo_page:
        class: %krg_seo.admin.seo_page.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: "SEO", label: "SEO Page" }
        arguments:
            - ~
            - '%krg_seo.seo_page_class%'
            - ~
        calls:
            - [setSeoFormRegistry, ['@krg_seo.form.registry']]
            - [setRouter, ['@router']]
            - [setEntityManager, ['@sonata.admin.entity_manager']]
            - [setClearCache, ['@krg_seo.clear_routing_cache']]

    krg_seo.clear_routing_cache:
        class: KRG\SeoBundle\DependencyInjection\ClearRoutingCache
        calls:
            - [setRouter, ['@router']]
            - [setFilesystem, ['@filesystem']]
            - [setKernel, ['@kernel']]
