easy_admin:
    entities:
        Seo:
            class: '%easy_admin_seo_class%'
            controller: KRG\SeoBundle\Admin\Controller\SeoController
            list:
                fields: ['route', 'metaTitle', 'metaDescription', 'parameters', 'url']
            new:
                fields: ['route']
            edit:
                fields:
                    - enabled
                    - url
                    - metaTitle
                    - { property: metaDescription, type: textarea }
                    - metaRobots
                    - ogTitle
                    - ogDescription
                    - ogImage
