imports:
    - { resource: easyadmin/ }

easy_admin:
    design:
        menu:
            -
                label: 'CMS'
                priority: 100
                roles: ['ROLE_CMS']
                children:
                    - { entity: 'Menu', icon: 'reorder', label: 'admin_menu.menu' }
                    - { entity: 'Page', icon: 'file', label: 'admin_menu.page' }
                    - { entity: 'Seo', icon: 'sitemap', roles: ['ROLE_SEO'], label: 'admin_menu.seo' }
                    - { entity: 'Block', icon: 'cubes', label: 'admin_menu.block' }
                    - { entity: 'Filter', icon: 'filter', label: 'admin_menu.filter' }
                    - { route: 'krg_cms_admin_media', icon: 'folder-open', label: 'admin_menu.media' }
