easy_admin:
    entities:
        Seo:
            class: '%easy_admin_seo_class%'
            controller: KRG\SeoBundle\Admin\Controller\SeoController
            templates:
                edit: '@KRGSeo/Admin/Seo/edit.html.twig'
            list:
                fields: ['enabled', 'route', 'metaTitle', 'metaDescription', 'parameters', 'url']
                dql_filter: "entity.route != 'krg_seo_page_show'"
            new:
                fields: ['route']
            edit:
                fields:
                    - enabled
                    - { property: url, label: 'Redirect url' }
                    - metaTitle
                    - { property: metaDescription, type: textarea }
                    - metaRobots
                    - ogTitle
                    - ogDescription
                    - ogImage

        SeoPage:
            class: '%easy_admin_seo_page_class%'
            controller: KRG\SeoBundle\Admin\Controller\SeoPageController
            templates:
                edit: '@KRGSeo/Admin/SeoPage/edit.html.twig'
            list:
                fields: [{ property: seo.enabled, type: toggle, label: 'Enabled' }, key, { property: seo.url, label: 'Url' }, formRoute, content]
            new:
                fields: [formType, { property: url, type: text, type_options: { required: true } }, formData]
            edit:
                fields:
                    - title
                    - formType
                    - { property: key, type: text, label: 'Identifier key' }
                    - preContent
                    - postContent
                    - { property: seo, type: KRG\SeoBundle\Form\Type\SeoPageSeoType }
