services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KRG\SeoBundle\Twig\:
        resource: '../../Twig/*'
        tags: [twig.extension]

    KRG\SeoBundle\Twig\BlockExtension:
        arguments:
            $cacheDir: '%kernel.cache_dir%'

    KRG\SeoBundle\Routing\SeoListener:
        tags: [{ name: kernel.event_listener, event: kernel.request }]

    KRG\SeoBundle\Routing\SeoLoader:
        tags: [routing.loader]

    KRG\SeoBundle\Form\SeoFormRegistry:
        public: true

    KRG\SeoBundle\DependencyInjection\ClearRoutingCache:

    KRG\SeoBundle\Admin\EventListener\:
        resource: '../../Admin/EventListener'
        tags: [kernel.event_subscriber]
