services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $twigCacheDir: '%kernel.cache_dir%/krg/twig'
            $dataCacheDir: '%kernel.cache_dir%/krg/data'
            $fileBlocks: '%krg_cms.blocks%'
            $rootDir: '%kernel.root_dir%'
            $seoParameters: '%krg_cms.seo%'
            $uploadDir: '/uploads/cms'
            $pageConfig: '%krg_cms.page%'
            $intlLocales: '%krg_cms.intl_locales%'

    KRG\CmsBundle\Twig\:
        resource: '../../Twig/*'
        tags: [twig.extension]

    KRG\CmsBundle\Form\Type\:
        resource: '../../Form/Type/*'
        tags: [form.type]

    KRG\CmsBundle\Service\:
        resource: '../../Service/*'
        public: true

    KRG\CmsBundle\Finder\:
        resource: '../../Finder/*'
        public: true

    KRG\CmsBundle\Menu\:
        resource: '../../Menu/*'
        public: true

    KRG\CmsBundle\Routing\SeoListener:
        tags: [{ name: kernel.event_listener, event: kernel.request }]

    KRG\CmsBundle\Routing\SeoLoader:
        tags:
            - {name: 'routing.loader', priority: 100}

    KRG\CmsBundle\Routing\RoutingLoader:
        tags:
            - 'routing.loader'

    KRG\CmsBundle\Form\FilterRegistry:
        public: true

    KRG\CmsBundle\Util\:
        resource: '../../Util/*'
        public: true

    KRG\CmsBundle\Entity\Listener\:
        resource: '../../Entity/Listener/*'
        tags: [doctrine.event_subscriber]
        public: true

    KRG\CmsBundle\Entity\Validator\:
        resource: '../../Entity/Validator/*'
        tags: [validator.constraint_validator]
        public: true

    KRG\CmsBundle\Entity\Subscriber\:
        resource: '../../Entity/Subscriber/*'
        tags: [kernel.event_subscriber]
        public: true

    KRG\CmsBundle\Menu\MenuBuilderInterface: '@KRG\CmsBundle\Menu\MenuBuilder'

    KRG\CmsBundle\Toolbar\:
        resource: '../../Toolbar'
        tags: [{name: 'krg.easyadmin.toolbar', priority: 500}]
        public: true
