services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $cacheDir: '%kernel.cache_dir%'
            $fileBlocks: '%krg_cms.blocks%'
            $rootDir: '%kernel.root_dir%'

    KRG\CmsBundle\Twig\:
        resource: '../../Twig/*'
        tags: [twig.extension]

    KRG\CmsBundle\Form\Type\:
        resource: '../../Form/Type/*'
        tags: [form.type]

    KRG\CmsBundle\Service\:
        resource: '../../Service/*'
        public: true

    KRG\CmsBundle\Menu\:
        resource: '../../Menu/*'
        public: true

    KRG\CmsBundle\Routing\SeoListener:
        tags: [{ name: kernel.event_listener, event: kernel.request }]

    KRG\CmsBundle\Routing\SeoLoader:
        tags: [routing.loader]

    KRG\CmsBundle\Form\FilterRegistry:
        public: true

    KRG\CmsBundle\Util\:
        resource: '../../Util/*'
        public: true

    KRG\CmsBundle\Entity\Listener\:
        resource: '../../Entity/Listener/*'
        tags: [doctrine.event_subscriber]
        public: true

    KRG\CmsBundle\Entity\Validator\:
        resource: '../../Entity/Validator/*'
        tags: [validator.constraint_validator]
        public: true

    KRG\CmsBundle\DependencyInjection\ClearCache:
        arguments:
            $cacheDir: '%kernel.cache_dir%'

    KRG\CmsBundle\Menu\MenuBuilderInterface: '@KRG\CmsBundle\Menu\MenuBuilder'
