services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $cacheDir: '%kernel.cache_dir%'
            $webDir: '%kernel.root_dir%/../web'
            $ckUploadDir: 'ckeditor/uploads'
            $blocks: '%krg_cms.blocks%'

    KRG\CmsBundle\Twig\:
        resource: '../../Twig/*'
        tags: [twig.extension]

    KRG\CmsBundle\Form\Type\:
        resource: '../../Form/Type/*'
        tags: [form.type]

    KRG\CmsBundle\Form\Extension\CKEditorTypeExtension:
        class: KRG\CmsBundle\Form\Extension\CKEditorTypeExtension
        tags:
            - {name: form.type_extension, extended_type: Ivory\CKEditorBundle\Form\Type\CKEditorType}

    KRG\CmsBundle\Menu\:
        resource: '../../Menu/*'
        public: true

    KRG\CmsBundle\Routing\SeoListener:
        tags: [{ name: kernel.event_listener, event: kernel.request }]

    KRG\CmsBundle\Routing\SeoLoader:
        tags: [routing.loader]

    KRG\CmsBundle\Form\FilterRegistry:
        public: true

    KRG\CmsBundle\Util\:
        resource: '../../Util/*'
        public: true

    KRG\CmsBundle\Entity\Listener\:
        resource: '../../Entity/Listener/*'
        tags: [doctrine.event_subscriber]
        public: true

    KRG\CmsBundle\Entity\Validator\:
        resource: '../../Entity/Validator/*'
        tags: [validator.constraint_validator]
        public: true

    KRG\CmsBundle\DependencyInjection\ClearCache:
        arguments:
            $cacheDir: '%kernel.cache_dir%'

    KRG\CmsBundle\Menu\MenuBuilderInterface: '@KRG\CmsBundle\Menu\MenuBuilder'
