services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KRG\SeoBundle\Twig\:
        resource: '../../Twig/*'
        tags: [twig.extension]

    KRG\SeoBundle\Form\Type\:
        resource: '../../Form/Type/*'
        tags: [form.type]

    KRG\SeoBundle\Menu\:
        resource: '../../Menu/*'
        public: true

    KRG\SeoBundle\Twig\BlockExtension:
        arguments:
            $cacheDir: '%kernel.cache_dir%'

    KRG\SeoBundle\Menu\MenuBuilder:
        arguments:
            $cacheDir: '%kernel.cache_dir%'

    KRG\SeoBundle\Routing\SeoListener:
        tags: [{ name: kernel.event_listener, event: kernel.request }]

    KRG\SeoBundle\Routing\SeoLoader:
        tags: [routing.loader]

    KRG\SeoBundle\Form\SeoFormRegistry:
        public: true

    KRG\SeoBundle\Entity\Listener\:
        resource: '../../Entity/Listener/*'
        tags: [doctrine.event_subscriber]
        public: true

    KRG\SeoBundle\Entity\Validator\:
        resource: '../../Entity/Validator/*'
        tags: [validator.constraint_validator]
        public: true

    KRG\SeoBundle\DependencyInjection\ClearCache:
        arguments:
            $cacheDir: '%kernel.cache_dir%'

    KRG\SeoBundle\Menu\MenuBuilderInterface: '@KRG\SeoBundle\Menu\MenuBuilder'
