easy_admin:
    entities:
        BlockForm:
            class: '%easy_admin_seo_block_form_class%'
            list:
                fields:
                    - enabled
                    - working
                    - key
                    - name
            form:
                fields:
                    - enabled
                    - name
                    - { property: key, type_options: { required: true } }
                    - { property: form, type: KRG\SeoBundle\Form\Type\SeoFormType }
