easy_admin:
    entities:
        BlockForm:
            class: '%easy_admin_seo_block_form_class%'
            list:
                fields:
                    - key
                    - name
                    - { property: enabled, type: toggle }
            form:
                fields:
                    - key
                    - name
                    - route
                    - type
                    - data