easy_admin:
    entities:
        BlockForm:
            class: '%easy_admin_seo_block_form_class%'
            list:
                fields:
                    - key
                    - name
                    - enabled
            form:
                fields:
                    - name
                    - key
                    - {property: form, type: KRG\SeoBundle\Form\Type\SeoFormType }
