easy_admin:
    entities:
        Filter:
            class: 'KRG\CmsBundle\Entity\FilterInterface'
            list:
                title: '<i class="fa fa-filter"></i> Filters'
                fields:
                    - { property: key, label: 'filter.key' }
                    - { property: name, label: 'filter.name' }
                    - { property: 'working', type: 'boolean', label: 'filter.working' }
                    - { property: enabled, label: 'filter.enabled' }
            form:
                fields:
                    - { type: 'group', label: 'group.configuration' }
                    - { property: key, type_options: { required: true }, label: 'filter.key' }
                    - { property: name, label: 'filter.name' }
                    - { type: 'group', label: 'group.form' }
                    - { property: form, type: KRG\CmsBundle\Form\Type\FilterType }
                    - { type: 'group', label: 'group.status' }
                    - { property: enabled, label: 'filter.enabled' }
