easy_admin:
    entities:
        Filter:
            class: 'KRG\CmsBundle\Entity\FilterInterface'
            list:
                fields:
                    - { property: 'name', label: 'filter.name' }
                    - { property: 'seo', label: 'Seo', type: 'boolean' }
                    - { property: 'working', type: 'boolean', label: 'filter.working' }
                    - { property: 'enabled', label: 'filter.enabled' }
            form:
                fields:
                    - { type: 'group', label: 'group.filter' }
                    - { property: name, label: 'filter.name' }
                    - { type: 'group', label: 'group.configuration' }
                    -
                        property: 'seo'
                        type: 'KRG\CmsBundle\Form\Type\SeoType'
                        label: false
                        type_options:
                            required_url: false
                    - { type: 'group', label: 'group.form' }
                    - { property: 'form', type: 'KRG\CmsBundle\Form\Type\FilterType' }
                    - { type: 'group', label: 'group.status' }
                    - { property: 'enabled', label: 'filter.enabled' }
