easy_admin:
    entities:
        Filter:
            class: '%krg_cms.filter.class%'
            list:
                fields:
                    - enabled
                    - { property: 'working', type: 'boolean' }
                    - key
                    - name
            form:
                fields:
                    - enabled
                    - name
                    - { property: key, type_options: { required: true } }
                    - { property: form, type: KRG\CmsBundle\Form\Type\FilterType }
