easy_admin:
    entities:
        Menu:
            class: 'KRG\CmsBundle\Entity\MenuInterface'
            list:
                title: '<i class="fa fa-bars"></i> Menu'
                fields:
                    - name
                    - url
                    - enabled
                sort: ['position', 'ASC']
            form:
                fields:
                    - { property: key, help: 'Unique identifier' }
                    - name
                    - { property: route, type: KRG\CmsBundle\Form\Type\UrlType, label: 'URL' }
                    - parent
                    - enabled
