easy_admin:
    entities:
        Menu:
            class: 'KRG\CmsBundle\Entity\MenuInterface'
            list:
                max_results: 100
                fields:
                    - 'name'
                    - 'url'
                    - 'parent'
                    - 'enabled'
                sort: ['position', 'ASC']
            form:
                fields:
                    - { type: 'group', label: 'menu' }
                    - 'name'
                    - { property: 'key', help: 'unique_key', label: 'menu.key'  }
                    - 'parent'
                    - 'icon'
                    - { type: 'group', label: 'configuration' }
                    - 'route'
                    - { type: 'group', label: 'content' }
                    - 'content'
                    - 'breadcrumbDisplay'
                    - 'enabled'
