easy_admin:
    entities:
        Menu:
            class: 'KRG\CmsBundle\Entity\MenuInterface'
            list:
                max_results: 100
                fields:
                    - 'nameAndDeepness'
                    - 'url'
                    - 'parent'
                    - 'enabled'
                sort: ['position', 'ASC']
            form:
                fields:
                    - { type: 'group', label: 'Menu' }
                    - 'name'
                    - { property: 'key', help: 'unique_key' }
                    - 'parent'
                    - 'icon'
                    - 'breadcrumbDisplay'
                    - { type: 'group', label: 'Configuration' }
                    - { property: 'route', type: 'KRG\CmsBundle\Form\Type\UrlType', label: false }
                    - { type: 'group', label: 'Content', collapsible: true }
                    -   property: 'content'
                        label: false
                        type_options:
                            fragment: true
                    - { type: 'group', label: 'Status' }
                    - 'enabled'
