easy_admin:
    entities:
        Menu:
            class: '%easy_admin_seo_menu_class%'
            list:
                fields:
                    - enabled
                    - name
                    - parent
                    - title
                    - url
                sort: ['position', 'ASC']
                actions:
                    - { name: 'sortable', field: 'position', label: '' }
            form:
                fields:
                    - enabled
                    - name
                    - { property: key, help: 'Unique identifier' }
                    - parent
                    - title
                    - { property: route, type: KRG\SeoBundle\Form\Type\SeoRouteType }
                    - url
