easy_admin:
    entities:
        Menu:
            class: '%krg_cms.menu.class%'
            list:
                title: '<i class="fa fa-bars"></i> Menu'
                fields:
                    - enabled
                    - name
                    - url
                sort: ['position', 'ASC']
                actions:
                    - { name: 'sortable', field: 'position', label: '' }
            form:
                fields:
                    - enabled
                    - { property: key, help: 'Unique identifier' }
                    - name
                    - { property: route, type: KRG\CmsBundle\Form\Type\UrlType, label: 'Url' }
                    - parent
