easy_admin:
    entities:
        Page:
            class: '%krg_cms.page.class%'
            list:
                fields:
                    - enabled
                    - name
                    - { property: seo.url, label: 'Url' }
            form:
                fields:
                    - name
                    - { property: seo, type: KRG\CmsBundle\Form\Type\SeoType }
                    - { property: 'content', type: 'ckeditor' }
                    - enabled
