easy_admin:
    entities:
        Page:
            class: '%krg_cms.page.class%'
            list:
                title: '<i class="fa fa-file"></i> Page'
                fields:
                    - name
                    - { property: seo.metaTitle, label: 'Title' }
                    - { property: seo.url, label: 'Url' }
                    - enabled
                actions:
                    - { name: 'krg_page_admin_show', type: 'route', label: 'action.show' }
            form:
                fields:
                    - name
                    -
                        property: seo
                        type: KRG\CmsBundle\Form\Type\SeoType
                        label: false
                    -
                        property: 'content'
                        type: KRG\IntlBundle\Form\Type\TranslationType
                        type_options:
                            entry_type: KRG\CmsBundle\Form\Type\ContentType
                            entry_options:
                                fragment: false
                    - enabled
