easy_admin:
    entities:
        Page:
            class: 'KRG\CmsBundle\Entity\PageInterface'
            list:
                fields:
                    - 'name'
                    - 'seo.metaTitle'
                    - 'seo.url'
                    - 'enabled'
                actions:
                    - { name: 'clone', icon: 'clone', css_class: 'btn btn-secondary', menu_dropdown: true }
            form:
                fields:
                    - { type: 'group', label: 'Page'}
                    - 'name'
                    - 'content'
                    - { type: 'group', label: 'SEO'}
                    - 'seo'
                    - 'enabled'
