easy_admin:
    entities:
        Page:
            class: '%krg_cms.page.class%'
            list:
                title: '<i class="fa fa-file"></i> Page'
                fields:
                    - enabled
                    - name
                    - { property: seo.url, label: 'Url' }
                actions:
                    - { name: 'krg_page_admin_show', type: 'route', label: '', icon: 'eye' }
            form:
                fields:
                    - name
                    -
                        property: 'content'
                        type: KRG\CmsBundle\Form\Type\ContentType
                        type_options:
                            switch_header_footer: true
                    - { property: seo, type: KRG\CmsBundle\Form\Type\SeoType }
                    - enabled
