easy_admin:
    entities:
        Page:
            class: 'KRG\CmsBundle\Entity\PageInterface'
            list:
                title: '<i class="fa fa-file"></i> Page'
                fields:
                    - { property: name, label: 'page.name' }
                    - { property: seo.metaTitle, label: 'seo.title' }
                    - { property: seo.url, label: 'seo.url' }
                    - { property: enabled, label: 'page.enabled' }
                actions:
                    - { name: 'clone', icon: 'clone', css_class: 'btn btn-secondary' }
            form:
                fields:
                    - { property: name, label: 'page.name' }
                    -
                        property: seo
                        type: KRG\CmsBundle\Form\Type\SeoType
                        label: false
                    -
                        property: 'content'
                        type: KRG\CmsBundle\Form\Type\ContentType
                        entry_options:
                            fragment: false
                    - { property: enabled, label: 'page.enabled' }
