easy_admin:
    entities:
        Seo:
            class: '%krg_cms.seo.class%'
            list:
                title: '<i class="fa fa-sitemap"></i> Seo'
                fields:
                    - url
                    - { property: routeName, label: 'Route' }
                    - metaTitle
                    - metaDescription
                    - enabled
            form:
                fields:
                    - { type: 'group', label: 'Configuration' }
                    - { property: route, type: KRG\CmsBundle\Form\Type\RouteType }
                    - { property: url, label: 'Redirect URL' }
                    - { type: 'group', label: 'Metas' }
                    - metaTitle
                    - { property: metaDescription, type: textarea }
                    - enabled
