easy_admin:
    entities:
        Seo:
            class: '%easy_admin_seo_class%'
            controller: KRG\SeoBundle\Admin\Controller\SeoController
            templates:
                edit: '@KRGSeo/Admin/Seo/edit.html.twig'
            list:
                fields: ['enabled', 'route', 'metaTitle', 'metaDescription', 'parameters', 'url']
                dql_filter: "entity.route != 'krg_seo_page_show'"
            new:
                fields: ['route']
            edit:
                fields:
                    - enabled
                    - { property: url, label: 'Redirect url' }
                    - metaTitle
                    - { property: metaDescription, type: textarea }
                    - metaRobots
                    - ogTitle
                    - ogDescription
                    - ogImage