easy_admin:
    entities:
        Seo:
            roles: ['ROLE_SEO']
            class: 'KRG\CmsBundle\Entity\SeoInterface'
            list:
                fields:
                    - 'url'
                    - 'routeName'
                    - 'metaTitle'
                    - 'enabled'
            form:
                fields:
                    - { type: 'group', label: 'configuration' }
                    - 'route'
                    - 'url'
                    - { type: 'group', label: 'metas' }
                    - { property: 'metaTitle', attr: {data-route-selector: 'true'} }
                    - 'metaDescription'
                    - { type: 'group', label: 'content' }
                    - 'preContent'
                    - 'postContent'
                    - 'enabled'
