easy_admin:
    entities:
        Seo:
            class: '%easy_admin_seo_class%'
            list:
                fields:
                    - enabled
                    - url
                    - routeName
                    - metaTitle
                    - metaDescription
            form:
                fields:
                    - { type: 'group', label: 'Configuration' }
                    - { property: route, type: KRG\SeoBundle\Form\Type\SeoRouteType }
                    - { property: url, label: 'Redirect url' }
                    - enabled
                    - { type: 'group', label: 'Metas' }
                    - metaTitle
                    - { property: metaDescription, type: textarea }
                    - metaRobots
                    - ogTitle
                    - ogDescription
                    - ogImage
