easy_admin:
    entities:
        Seo:
            roles: ['ROLE_SEO']
            class: 'KRG\CmsBundle\Entity\SeoInterface'
            list:
                fields:
                    - 'url'
                    - 'routeName'
                    - 'metaTitle'
                    - 'enabled'
            form:
                fields:
                    - { type: 'group', label: 'Configuration' }
                    - { property: 'route', label: false }
                    - { property: 'url', label: 'Url redirect' }
                    - { type: 'group', label: 'Metas' }
                    - { property: 'metaTitle', attr: {data-route-selector: 'true'} }
                    - 'metaDescription'
                    - { type: 'group', label: 'Robots' }
                    - 'noIndex'
                    - 'noFollow'
                    - { type: 'group', label: 'Content', collapsible: true }
                    - 'preContent'
                    - 'postContent'
                    - { type: 'group', label: 'Status' }
                    - 'enabled'
