easy_admin:
    entities:
        Seo:
            roles: ['ROLE_SEO']
            class: 'KRG\CmsBundle\Entity\SeoInterface'
            list:
                title: '<i class="fa fa-sitemap"></i> Seo'
                dql_filter:
                fields:
                    - { property: url, label: 'seo.url' }
                    - { property: routeName, label: 'seo.route' }
                    - { property: metaTitle, label: 'seo.metaTitle' }
                    - { property: priority, label: 'seo.priority' }
                    - { property: enabled, label: 'seo.enabled' }
            form:
                fields:
                    - { type: 'group', label: 'group.configuration' }
                    - { property: route, type: KRG\CmsBundle\Form\Type\RouteType }
                    - { property: url, label: 'seo.url_redirect' }
                    - { type: 'group', label: 'group.metas' }
                    - { property: metaTitle, label: 'seo.metaTitle' }
                    - { property: metaDescription, type: textarea, label: 'seo.metaDescription' }
                    - { type: 'group', label: 'group.content' }
                    -
                        property: 'preContent'
                        label: 'seo.preContent'
                        type: KRG\CmsBundle\Form\Type\ContentType
                        type_options:
                            height: 200
                    -
                        property: 'postContent'
                        label: 'seo.postContent'
                        type: KRG\CmsBundle\Form\Type\ContentType
                        type_options:
                            height: 200
                    - { type: 'group', label: 'group.status' }
                    - { property: priority, label: 'seo.priority', help: 'priority_help', type_options: { required: false } }
                    - { property: enabled, label: 'seo.enabled' }
