easy_admin:
    entities:
        Seo:
            roles: ['ROLE_SEO']
            class: 'KRG\CmsBundle\Entity\SeoInterface'
            list:
                title: '<i class="fa fa-sitemap"></i> Seo'
                dql_filter:
                fields:
                    - { property: url, label: 'seo.url' }
                    - { property: routeName, label: 'seo.route' }
                    - { property: metaTitle, label: 'seo.metaTitle' }
                    - { property: enabled, label: 'seo.enabled' }
            form:
                fields:
                    - { type: 'group', label: 'group.configuration' }
                    - { property: route, type: KRG\CmsBundle\Form\Type\RouteType }
                    - { property: url, label: 'seo.url_redirect' }
                    - { type: 'group', label: 'group.metas' }
                    - { property: metaTitle, label: 'seo.metaTitle' }
                    - { property: metaDescription, type: textarea, label: 'seo.metaDescription' }
                    - { type: 'group', label: 'group.content' }
                    - { property: preContent, type: textarea, label: 'seo.preContent' }
                    - { property: postContent, type: textarea, label: 'seo.postContent' }
                    - { type: 'group', label: 'group.status' }
                    - { property: enabled, label: 'seo.enabled' }
